name: TestPlugin
version: '${project.version}'
main: com.github.mayankpatibandla.testplugin.TestPlugin
api-version: '1.20'
authors: [Mayank Patibandla (xTigr)]
description: Just messing around with Spigot
website: https://github.com/mayankpatibandla/
