name: TestPlugin
version: '${project.version}'
main: com.github.mayankpatibandla.testplugin.TestPlugin
api-version: '1.20'
authors: [ Mayank Patibandla (xTigr) ]
description: Just messing around with Spigot
website: https://github.com/mayankpatibandla/

permissions:
  ${project.artifactId}.feed:
    description: Used by the feed command
    default: op

commands:
  slime:
    description: "Summons a slime of specified size (default: 3) at the sender's location"
    usage: /<command> [size]
  god:
    description: "Toggles the player's god mode"
    usage: /<command>
    aliases:
      - godmode
      - invincible
  feed:
    description: "Fills the player's hunger bar"
    usage: /<command> <player>
    permission: ${project.artifactId}.feed
    permission-message: Insufficient permission